src/AudioCapture.cpp, src/AudioCapture.h, src/ProjectMSDLApplication.cpp, src/ProjectMSDLApplication.h, src/ProjectMWrapper.h, src/SDLRenderingWindow.cpp, src/SDLRenderingWindow.h
Made some changes so that it could compile on my computer with Poco 1.9.2.
I opted for the smallest changes that would make it compile, but it could also be worthwhile to try moving from Poco's smart pointers to the ones available in the standard library.
=> Make code compile with older versions of Poco

src/CMakeLists.txt, src/ProjectMSDLApplication.cpp, src/main.cpp
Using SDL's main function is required on some platforms like Windows and macOS to perform some early initialization and cleanups on shutdown. Since SDL defines a `main` macro, this will replace the `ProjectMSDLApplication::main` function with `ProjectMSDLApplication::SDL_main`, which will break things.
To circumvent this, I needed to do a few things:
1. Move the main function that creates. the Poco application to its own implementation file.
2. No longer use Poco's `POCO_APP_MAIN` macro, as this defines the main function as `wmain` on Windows - SDL2 expects it as `main`.
3. Link the SDLmain static library.
4. Add `WIN32` in CMake's target definition to compile it as a GUI application, which will use the `WinMain` entry point and not show a console window.
=> Moved the main() function to a separate file and let SDL replace it with SDL_main properly.

CMakeLists.txt, src/AudioCapture.h, src/CMakeLists.txt, src/ProjectMWrapper.cpp, src/SDLRenderingWindow.cpp
- Removed a non-standard include that sneaked in.
- Replaced OS-specific OpenGL includes with SDL's OpenGL header.
- Link OpenGL library and apply SDL2 path fixes.
=> Few fixes to make the app compile properly on macOS.

src/AudioCaptureImpl_SDL.cpp
Renamed projectm_pcm_add_float calls in AudioCaptureImpl_SDL to match latest API in projectM.h .
frontend-sdl2 now builds against latest projectM.
=> Fixed projectm_pcm_add_float api change

CMakeLists.txt, cmake/SDL2Target.cmake, src/CMakeLists.txt
Had to increase the minimum CMake requirement to 3.15, otherwise the CMAKE_MSVC_RUNTIME_LIBRARY won't work and devs can't easily use the static runtime.
=> Added a few tweaks to be able to build the app as an all-static executable, using /MT[d] on Windows.

.github/workflows/build.yaml
Build on linux
Should add one for macOS
=> CI (Linux)

src/RenderLoop.cpp, src/RenderLoop.h
SDL's resize events are sometimes unreliable, e.g, if using the green "fullscreen" button on macOS or toggling to the borderless, non-exclusive fullscreen mode on Linux. Getting the GL drawable size is fast and also reliable, so we can simply check it on each frame. Will also take care of DPI changes.
=> Check viewport size every frame and resize projectM if changed.

src/ProjectMSDLApplication.cpp, src/ProjectMWrapper.cpp, src/resources/projectMSDL.properties.in
Add option to specify an additional texture path. Helpful if the user's custom preset dir doesn't contain all the Milkdrop textures or the user wants a specific image dir to be used.
Depends on https://github.com/projectM-visualizer/projectm/pull/624
=> Add texture path option

CMakeLists.txt, install.cmake, src/AudioCaptureImpl_SDL.cpp, src/CMakeLists.txt, src/resources/projectMSDL.properties.in
Three small improvements:
- Fix potentially using a nullptr in `std::string` construction
- Add default paths for presets and textures to the properties file and make them configurable via CMake variables
- Add (very basic) install commands for the executable and properties file
=> A couple of fixes and improvements

.github/workflows/build.yaml, CMakeLists.txt, src/AudioCaptureImpl_SDL.cpp, src/AudioCaptureImpl_SDL.h, src/CMakeLists.txt, src/ProjectMSDLApplication.cpp, src/ProjectMWrapper.cpp, src/ProjectMWrapper.h, src/RenderLoop.cpp, src/RenderLoop.h
Two issues with SDL audio capturing are fixed here:
1. The input buffer size was fixed to the maximum sample count stored by libprojectM (e.g. the internal sample buffer size), which is currently 2048 samples. This caused SDL to collect data until this size was reached, calling the audio callback only with about 21 FPS, which would only update waveforms every third frame making it look jaggy.  
Now, the input buffer size is set to match the target FPS value, and is clamped to a minimum of 300 samples (~144 FPS) and the maximum buffer size projectM can use (21 FPS). This should effctively smooth the waveform display even on high FPS monitors, while still working well with very low FPS settings.
2. The `projectm_pcm_add_float()` was only called with 1 or 2 channels, but if the channel count …
=> Fix SDL audio capture issues

CMakeLists.txt, README.md, dependencies_check.cmake, src/AudioCaptureImpl_SDL.cpp, src/AudioCaptureImpl_WASAPI.cpp, src/ProjectMSDLApplication.cpp, src/ProjectMWrapper.h
The SDL2 frontend would not build on my system. cmake complains:
```shell
CMake Error at CMakeLists.txt:27 (find_package):
By not providing "FindlibprojectM.cmake" in CMAKE_MODULE_PATH this project
has asked CMake to find a package configuration file provided by
"libprojectM", but CMake did not find one.
Could not find a package configuration file provided by "libprojectM" with
any of the following names:
libprojectMConfig.cmake
libprojectm-config.cmake
Add the installation prefix of "libprojectM" to CMAKE_PREFIX_PATH or set
"libprojectM_DIR" to a directory containing one of the above files.  If
"libprojectM" provides a separate development package or SDK, be sure it
has been installed.
```
I've updated several instances of `libprojectM` with `projectM4` in the cmake files, and updated …
=> updated cmake files

src/RenderLoop.cpp
Causes heap issues in Windows DLL-based builds otherwise.
=> Free strings from playlist library with the correct method.

.github/workflows/build.yaml, CMakeLists.txt, README.md, dependencies_check.cmake
Since the application will crash due to either heap corruption or double-free issues, it won't make much sense to allow people to compile it against affected versions.
=> Add version check for buggy Poco libraries.

.github/ISSUE_TEMPLATE/config.yml
Disables the default link for creating blank issues and adds a link to the main repo for new issues.
See PR https://github.com/projectM-visualizer/projectm/pull/801 for details.
=> Redirect users to file new bug reports in the main libprojectM repository.

.github/workflows/build.yaml
The Windows Platform SDK issue was fixed by GitHub, so we can remove the no longer working workaround.
Also updated the checkout action to v4.
=> Remove Windows build check workaround and update actions

src/ProjectMSDLApplication.cpp, src/RenderLoop.cpp, src/RenderLoop.h, src/gui/SettingsWindow.cpp
I wanted a good first issue to acquaint myself with this project, and since one of the frustrating parts of the build/install process was figuring out how to load presets, I figured adding good drag & drop support would be useful (as per issue https://github.com/projectM-visualizer/frontend-sdl-cpp/issues/84).
SDL provides the drop event, so the implementation was fairly straightforward. The user can either drag & drop a preset file (or collection of preset files), or a folder containing presets. Preset files are files that end with '.milk' or '.prjm' (haven't seen or used prjm files but they are listed as supported in the projectM code). Dragging a file will immediately enqueue it on the next spot in the playlist, and dragging a folder will enqueue all presets in the folder (searched …
=> Adding file/folder drop support

CMakeLists.txt
POCO 1.14. now requires C++17 to be used. This application doesn't have this hard requirement, so we now adapt the build process accordingly to use C++17 if POCO 1.14.0 or higher is found.
=> Use C++17 to build if we find POCO 1.14 or higher.

src/gui/ProjectMGUI.cpp, src/gui/ProjectMGUI.h, src/gui/SettingsWindow.cpp, src/gui/SettingsWindow.h, src/resources/projectMSDL.properties.in
On some platforms/displays, the auto-detected font size might be a bit too small or large, so we should let the user apply a custom scaling factor.
Since the existing sliders in the UI apply their value immediately, I had to add another one that has an apply button, as moving the sslider causes issues if the UI rescales immediately.
=> Add UI scaling option

src/AudioCaptureImpl_SDL.cpp
We can use any number of channels, so SDL2 can just give us the proper channel count for the given device. Might also cause issues when using the sdl2-compat layer for SDL3, as it may not be able to "emulate" channels.
Also display the audio driver used by SDL in log level "debug".
=> Allow SDL to change channel count and log audio driver.

src/AudioCaptureImpl_SDL.cpp
=> Close previous SDL audio recording device when selecting a new device index.

src/ProjectMWrapper.cpp, src/ProjectMWrapper.h, src/RenderLoop.cpp, src/gui/HelpWindow.cpp, src/gui/MainMenu.cpp
=> Add ctrl-c shortcut to copy current preset path to clipboard

src/ProjectMWrapper.cpp
Description also says "nect/prev preset in playlist", so it's better to disable shuffle when performing manual preset changes. A random preset can always be picked using the r key.
Fixes #78
=> Don't shuffle when manually using prev/next commands
